"""create words and translation options

Revision ID: 4629186736bf
Revises:
Create Date: 2026-07-14 12:22:59.039269

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4629186736bf"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "words",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_word", sa.String(length=128), nullable=False),
        sa.Column("source_language", sa.String(length=2), nullable=False),
        sa.Column("target_language", sa.String(length=2), nullable=False),
        sa.Column("slug", sa.String(length=150), nullable=False),
        sa.Column("transcription", sa.String(length=128), nullable=False),
        sa.Column("primary_translation", sa.String(length=256), nullable=False),
        sa.Column("context_sentence", sa.Text(), nullable=False),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_word_slug"),
        sa.UniqueConstraint(
            "source_word", "source_language", "target_language", name="uq_word_direction"
        ),
    )
    op.create_index(op.f("ix_words_slug"), "words", ["slug"], unique=False)
    op.create_index(op.f("ix_words_source_word"), "words", ["source_word"], unique=False)
    op.create_table(
        "translation_options",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=256), nullable=False),
        sa.Column("part_of_speech", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("usage_note", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["word_id"], ["words.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "word_id", "text", "part_of_speech", name="uq_translation_option_per_word"
        ),
    )
    op.create_index(
        op.f("ix_translation_options_word_id"), "translation_options", ["word_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_translation_options_word_id"), table_name="translation_options")
    op.drop_table("translation_options")
    op.drop_index(op.f("ix_words_source_word"), table_name="words")
    op.drop_index(op.f("ix_words_slug"), table_name="words")
    op.drop_table("words")
    # ### end Alembic commands ###
